package com.vernora.api.progress.infrastructure;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.Table;
import java.time.Instant;
import java.util.UUID;

/**
 * One graded answer, recorded forever. Append-only: this entity is inserted,
 * never updated, so it has no setters beyond what JPA needs.
 *
 * <p>Hibernate's default naming strategy maps camelCase fields to snake_case
 * columns (attemptId -> attempt_id), so no @Column names are needed. With
 * ddl-auto: validate, Hibernate checks this mapping against the Flyway-managed
 * schema at startup and refuses to boot on a mismatch.
 */
@Entity
@Table(name = "exercise_attempts")
public class ExerciseAttemptEntity {

    /** Surrogate key generated by Postgres ("generated always as identity"). */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /** Client-generated UUID; unique per user. This is the idempotency key. */
    @Column(nullable = false)
    private UUID attemptId;

    /** Derived from the JWT subject, never from the request body. */
    @Column(nullable = false)
    private UUID userId;

    @Column(nullable = false)
    private String courseId;

    @Column(nullable = false)
    private String lessonId;

    @Column(nullable = false)
    private String exerciseId;

    @Column(nullable = false)
    private String exerciseType;

    @Column(nullable = false)
    private boolean correct;

    /** When the learner answered, by the client's clock (offline-sync ready). */
    @Column(nullable = false)
    private Instant clientCreatedAt;

    /** When the server persisted it, by the server's clock. */
    @Column(nullable = false)
    private Instant createdAt;

    /** JPA requires a no-arg constructor; protected keeps it out of app code. */
    protected ExerciseAttemptEntity() {}

    public ExerciseAttemptEntity(
            UUID attemptId,
            UUID userId,
            String courseId,
            String lessonId,
            String exerciseId,
            String exerciseType,
            boolean correct,
            Instant clientCreatedAt) {
        this.attemptId = attemptId;
        this.userId = userId;
        this.courseId = courseId;
        this.lessonId = lessonId;
        this.exerciseId = exerciseId;
        this.exerciseType = exerciseType;
        this.correct = correct;
        this.clientCreatedAt = clientCreatedAt;
        this.createdAt = Instant.now();
    }

    public Long getId() {
        return id;
    }

    public UUID getAttemptId() {
        return attemptId;
    }

    public UUID getUserId() {
        return userId;
    }

    public String getCourseId() {
        return courseId;
    }

    public String getLessonId() {
        return lessonId;
    }

    public String getExerciseId() {
        return exerciseId;
    }

    public String getExerciseType() {
        return exerciseType;
    }

    public boolean isCorrect() {
        return correct;
    }

    public Instant getClientCreatedAt() {
        return clientCreatedAt;
    }

    public Instant getCreatedAt() {
        return createdAt;
    }
}
