import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { apiGet, apiPost } from "../../lib/api";
import { useSession } from "../../providers/session-provider";

/** Mirrors the API's CourseProgressResponse. */
export type CourseProgress = {
  courseId: string;
  lessons: Array<{
    lessonId: string;
    exercises: Array<{ exerciseId: string; everCorrect: boolean }>;
  }>;
};

export type AttemptSubmission = {
  /**
   * The idempotency key. Generated by the CALLER (not inside mutationFn),
   * so if React Query retries the request after a network failure, every
   * retry carries the same UUID and the server dedupes it.
   */
  attemptId: string;
  exerciseId: string;
  courseId: string;
  lessonId: string;
  exerciseType: string;
  /** The exercise's concept tags; this is what feeds mastery. */
  conceptIds: string[];
  correct: boolean;
};

export function useCourseProgress(courseId: string | undefined) {
  const { session } = useSession();
  return useQuery({
    // session user in the key: switching accounts must not show stale progress.
    queryKey: ["progress", courseId, session?.user.id],
    enabled: Boolean(courseId) && Boolean(session),
    queryFn: () =>
      apiGet<CourseProgress>(
        `/v1/courses/${courseId}/progress`,
        session!.access_token,
      ),
  });
}

export function useSubmitAttempt() {
  const { session } = useSession();
  const queryClient = useQueryClient();

  return useMutation({
    mutationFn: async (attempt: AttemptSubmission) => {
      // Guests can play lessons; there is just no account to record against.
      if (!session) return;
      await apiPost(
        `/v1/exercises/${attempt.exerciseId}/attempts`,
        {
          attemptId: attempt.attemptId,
          courseId: attempt.courseId,
          lessonId: attempt.lessonId,
          exerciseType: attempt.exerciseType,
          conceptIds: attempt.conceptIds,
          correct: attempt.correct,
          clientCreatedAt: new Date().toISOString(),
        },
        session.access_token,
      );
    },
    // Retries are safe precisely because attemptId makes the write idempotent.
    retry: 2,
    onSuccess: (_data, attempt) => {
      // Any cached progress and review schedule is now stale; refetch on
      // next use. (The review screen snapshots its queue at session start,
      // so an invalidation mid-session never reshuffles it.)
      void queryClient.invalidateQueries({
        queryKey: ["progress", attempt.courseId],
      });
      void queryClient.invalidateQueries({ queryKey: ["review-queue"] });
      void queryClient.invalidateQueries({
        queryKey: ["mastery", attempt.courseId],
      });
    },
  });
}

/** Mirrors the API's CourseMasteryResponse; concepts arrive weakest first. */
export type CourseMastery = {
  courseId: string;
  concepts: Array<{
    conceptId: string;
    attempts: number;
    recentAccuracy: number;
    masteryScore: number;
    lastAttemptAt: string;
  }>;
};

export function useCourseMastery(courseId: string | undefined) {
  const { session } = useSession();
  return useQuery({
    queryKey: ["mastery", courseId, session?.user.id],
    enabled: Boolean(courseId) && Boolean(session),
    queryFn: () =>
      apiGet<CourseMastery>(
        `/v1/courses/${courseId}/mastery`,
        session!.access_token,
      ),
  });
}

/** A lesson is complete when every one of its exercises was ever correct. */
export function isLessonComplete(
  progress: CourseProgress | undefined,
  lessonId: string,
  exerciseIds: string[],
): boolean {
  const lessonProgress = progress?.lessons.find(
    (lesson) => lesson.lessonId === lessonId,
  );
  if (!lessonProgress || exerciseIds.length === 0) return false;
  const correct = new Set(
    lessonProgress.exercises
      .filter((exercise) => exercise.everCorrect)
      .map((exercise) => exercise.exerciseId),
  );
  return exerciseIds.every((id) => correct.has(id));
}
